### ISSUE TITLE
where's the code?

### ISSUE THREAD

**Issue by goyalyashpal** [corbinlc/addi#77]
* i see the code tab to be completely empty

* also, what's the status of addi? like is it related to this : [com.gnuroot.octave](https://play.google.com/store/apps/details?id=com.gnuroot.octave) (repo: https://github.com/corbinlc/GNURootDebian ) ??

* and similarly, is this also FOSS: [com.addiPlot](https://play.google.com/store/apps/details?id=com.addiPlot)

**Comment by yashpalgoyal1304** [comment]
also, what's the status of addi?

like is it related to this : [com.gnuroot.octave](https://play.google.com/store/apps/details?id=com.gnuroot.octave) (repo: https://github.com/corbinlc/GNURootDebian ) ??
